### ISSUE TITLE
Problem with INIT_CODE_PAIR_HASH

### ISSUE THREAD

**Issue by johnwhitton** [KangaFinance/kanga#1]
**Describe the bug**
When generating and retrieving pairs using the UniswapV2Factory the INIT_CODE_PAIR_HASH appears to be different when deploying vs testing locally.

Believe the problem is similar to https://github.com/Uniswap/v2-core/issues/102

```
I found the cause of the problem.Because I did not use pre-compiled smart contracts.Instead I used truffle to compile smart contracts.When I compiled the CalHash contract with yarn compile，
```

**To Reproduce**
For deployment we use the hash generated by the following 

`const MANUAL_INIT_CODE_HASH = keccak256(['bytes'],[bytecode]);`

which is `0x2b3916d184be5391113dc61053ef6e55b1214905619aa198de8ef903f9acffd2`

And we have added this value to the [UniswapV2Library.sol](https://github.com/KangaFinance/kanga/blob/v0.1.0/contracts/uniswapv2/libraries/UniswapV2Library.sol#L26) minus the 0x prefix.
You can see the value returned on Kovan using the [UniswapV2Factory in explorer](https://kovan.etherscan.io/address/0xe11e6862f1fda04be02845afd000161b5caa05eb#readContract)

However when running [00_InitHash.test.ts](https://github.com/KangaFinance/kanga/blob/v0.1.0/test/00_InitHash.test.ts#L40) we get the value `0xb96a05d90581cfac1f99c92b02f2e69fbca4e5c26498be0dc204d91318c9f56b`

and when trying to [addLiquidity](https://github.com/KangaFinance/kanga/blob/v0.1.0/test/00_InitHash.test.ts#L40)
`    await addLiquidityKLP(this, "kangaEth", this.kanga, this.weth, "6000000000000000000", "6000000000000000000", "60000000000000000000", "6000000000000000000", this.alice.address)`

we get the following error
```
 2) KangaMaker
       checkInitHash
         check ability to add liquidity:
     Error: Transaction reverted: function call to a non-contract account
      at UniswapV2Router02.getReserves (contracts/uniswapv2/libraries/UniswapV2Library.sol:33)
      at UniswapV2Router02._addLiquidity (contracts/uniswapv2/UniswapV2Router02.sol:46)
      at UniswapV2Router02.addLiquidity (contracts/uniswapv2/UniswapV2Router02.sol:72)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at EthModule._estimateGasAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:402:9)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
      at EthersProviderWrapper.send (node_modules/hardhat-deploy-ethers/src/ethers-provider-wrapper.ts:13:20)
```

This can be resolved by updating And we have added this value to the [UniswapV2Library.sol](https://github.com/KangaFinance/kanga/blob/v0.1.0/contracts/uniswapv2/libraries/UniswapV2Library.sol#L26) to `b96a05d90581cfac1f99c92b02f2e69fbca4e5c26498be0dc204d91318c9f56b` but then deployments are broken

**Expected behavior**
1. The same init_hash can be used for testing and deployment
2. Adding liquidity works for testing and deployments.

**Actual behavior**
1. init_hash is different for testing and deployments
2. Adding liquidity fails when using the wrong init_hash

**Additional context**
Reference tickets
* [Uniswap addLiquidity function transaction revert](https://ethereum.stackexchange.com/questions/88075/uniswap-addliquidity-function-transaction-revert)
* [How to generate init code pair hash](https://github.com/Uniswap/v2-core/issues/102)
* [What is init code hash](https://ethereum.stackexchange.com/questions/89680/what-is-init-code-hash-and-how-is-it-calculated-used-in-defi-smart-contracts)

**Comment by johnwhitton** [comment]
Development steps updated in [DEVELOPMENT.md](https://github.com/KangaFinance/kanga/blob/master/docs/DEVELOPMENT.md)
```
# Modify the Factory Contract

# Run 00_InitHash.test.ts
yarn  hardhat test ./test/00_InitHash.test.ts

# Update the InitHash in the Library if needed contracts->uniswapv2->libraries->UniswapV2Library.sol


# Run 00_InitHash.test.ts
yarn  hardhat test ./test/00_InitHash.test.ts

# Modify the code in deploy->UniswapV2Factory and do initial deploy
yarn hardhat --network harmony-testnet deploy --tags UniswapV2Factory --reset
ll deployments/harmony-testnet/
cp deployments/harmony-testnet/UniswapV2Factory.json deployments/master/UniswapV2Factory.json
ll deployments/master/

# Modify the code in deploy->UniswapV2Pair and do initial deploy
yarn hardhat --network harmony-testnet deploy --tags UniswapV2Pair --reset
ll deployments/harmony-testnet/
cp deployments/harmony-testnet/UniswapV2Pair.json deployments/master/UniswapV2Pair.json
ll deployments/master/

# Revert the code back in deploy UniswapV2Factory and UniswapV2Pair

# Run 00_InitHash.test.ts
yarn  hardhat test ./test/00_InitHash.test.ts

# Deploy to testnet
yarn harmony-testnet:reset

```

**Comment by ckukner** [comment]
maybe it wasn't very clear but which one allowed you to migrate
0x2b3916d184be5391113dc61053ef6e55b1214905619aa198de8ef903f9acffd2
or
0xb96a05d90581cfac1f99c92b02f2e69fbca4e5c26498be0dc204d91318c9f56b
